default:
   google_email: "therossyndicate@gmail.com"
   chl_stable: TRUE
   chl_create_stable: FALSE
create_new_version:
   google_email: ""
   chl_stable: FALSE
   chl_create_stable: FALSE
admin_update:
  google_email: "therossyndicate@gmail.com"
  # Use a stable version of the chlorophyll data?
  chl_stable: FALSE
  # Create a stable version of chlorophyll data from this run?
  chl_create_stable: TRUE